apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orientdb-pv-claim
  labels:
    service: orientdb
    type: pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
 name: orientservice
spec:
 selector:
  app: orientservice
  tier: orient
 type: NodePort
 ports:
  - name: http
    port: 2480
    targetPort: http
    nodePort: 32480
    protocol: TCP
  - name: binary
    port: 2424
    targetPort: http2
    nodePort: 32424
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientservice
spec:
 selector:
  matchLabels:
   app: orientservice
   tier: orient
   track: stable
 replicas: 1
 template:
  metadata:
   labels:
    app: orientservice
    tier: orient
    track: stable
  spec:
   containers:
   - name: orientservice
     image: orientdb:3.0.18
     env:
     - name: ORIENTDB_ROOT_PASSWORD
       valueFrom:
         secretKeyRef:
           name: orientdb-pass
           key: password.txt
     ports:
      - name: http
        containerPort: 2480
      - name: http2
        containerPort: 2424
